# ----------------------- #
#      Main Configs       #
# ----------------------- #

# Site settings
url: http://mvj3.github.io
title: 世界的审美！
_subtitle: 物质的奴隶，时尚的仆人，内在的国王，艺术的上帝。
author: mvj3
email: mvjome@gmail.com
description: >
  An avid open-source full-stack engineer.
  Works include [Human programming language](http://human-lang.org), [luiti](https://github.com/17zuoye/luiti), [statlysis](https://github.com/mvj3/statlysis) etc.
twitter_username: mvj3
github_username:  mvj3
simple_search: http://google.com/search

# Build settings
markdown: kramdown # [rdiscount, kramdown]
excerpt_separator: ""  # Fixed via http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
permalink: /:year/:month/:day/:title.html

collections:
  static_html:
    output: true


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Disqus Comments
disqus: mvj3

# Google Analytics
google_analytics: UA-19059295-1

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
