# ----------------------- #
#      Main Configs       #
# ----------------------- #

# Site settings
url: http://mvj3.github.io
title: 世界的审美！
subtitle: 物质的奴隶，时尚的仆人，内在的国王，艺术的上帝。
author: mvj3
twitter_username: mvj3
github_username:  mvj3
simple_search: http://google.com/search

# Build settings
markdown: rdiscount # [rdiscount, kramdown]

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Disqus Comments
disqus_short_name: mvj3
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-19059295-1
