# ----------------------- #
#      Main Configs       #
# ----------------------- #

# Site settings
url: http://mvj3.github.io
title: 世界的审美！
_subtitle: 物质的奴隶，时尚的仆人，内在的国王，艺术的上帝。
author: mvj3
email: mvjome@gmail.com
description: >
  An avid open-source full-stack engineer.
  Works include <a href="http://human-lang.org">Human programming language</a>, <a href="https://github.com/17zuoye/luiti">luiti</a>, and <a href="https://github.com/mvj3/statlysis">statlysis</a>, etc.
twitter_username: mvj3
github_username:  mvj3
simple_search: http://google.com/search

# Build settings
markdown: kramdown # [rdiscount, kramdown]
excerpt_separator: ""  # Fixed via http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
permalink: /:year/:month/:day/:title.html

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Disqus Comments
disqus_short_name: mvj3
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-19059295-1
